"""Circuit configurations for the 2026 regulation era.

Each circuit defines its track segments (corners, straights) with energy
deployment, regeneration, and overtake characteristics. These feed the
Circuit Energy Difficulty Index, the energy deployment predictor, and the
strategy simulator.

Data is derived from public circuit maps and FIA track characteristics for the
2026 season. Segments are ordered by distance through a lap.
"""

from __future__ import annotations

from pitwall.regulations import CircuitConfig, TrackSegment

# ── Sector helpers ────────────────────────────────────────────────────────


def _sector(pct_start: float, pct_end: float, length_m: float) -> TrackSegment:
    """Helper to create a generic sector segment."""
    return TrackSegment(
        name=f"Sectors {pct_start:.0%}-{pct_end:.0%}",
        seg_type="STRAIGHT" if (pct_end - pct_start) > 0.15 else "CORNER",
        start_pct=pct_start,
        end_pct=pct_end,
        length_m=length_m,
    )


# ── Individual circuits ───────────────────────────────────────────────────


def bahrain_sakhir_2026() -> CircuitConfig:
    """Bahrain International Circuit — night race, heavy energy deployment on long straights."""
    return CircuitConfig(
        circuit_key="63",
        circuit_short_name="Sakhir",
        circuit_name="Bahrain International Circuit",
        country="Bahrain",
        total_laps=57,
        segments=[
            TrackSegment(
                "Turn 1 (Heavy Braking)",
                "CORNER",
                0.00,
                0.05,
                160,
                key_accel_zone=False,
                overtake_value=0.90,
                downforce_demand=0.85,
                regen_potential=0.80,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Start-Finish Straight",
                "STRAIGHT",
                0.05,
                0.20,
                1050,
                key_accel_zone=True,
                overtake_value=0.95,
                downforce_demand=0.10,
                regen_potential=0.10,
                max_speed_kmh=325,
            ),
            TrackSegment(
                "Turn 2-3 Complex",
                "CORNER",
                0.20,
                0.28,
                400,
                key_accel_zone=False,
                overtake_value=0.20,
                downforce_demand=0.75,
                regen_potential=0.55,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Back Straight",
                "STRAIGHT",
                0.28,
                0.50,
                1100,
                key_accel_zone=True,
                overtake_value=0.85,
                downforce_demand=0.15,
                regen_potential=0.05,
                max_speed_kmh=330,
            ),
            TrackSegment(
                "Turn 8-9 Chicane",
                "CHICANE",
                0.50,
                0.58,
                350,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.90,
                regen_potential=0.75,
                max_speed_kmh=240,
            ),
            TrackSegment(
                "Pit Straight",
                "STRAIGHT",
                0.58,
                0.66,
                250,
                key_accel_zone=True,
                overtake_value=0.60,
                downforce_demand=0.20,
                regen_potential=0.15,
                max_speed_kmh=315,
            ),
            TrackSegment(
                "Turn 10-11",
                "CORNER",
                0.66,
                0.80,
                550,
                key_accel_zone=False,
                overtake_value=0.15,
                downforce_demand=0.80,
                regen_potential=0.60,
                max_speed_kmh=280,
            ),
            TrackSegment(
                "Turn 12-13-14",
                "CORNER",
                0.80,
                0.95,
                700,
                key_accel_zone=False,
                overtake_value=0.25,
                downforce_demand=0.85,
                regen_potential=0.65,
                max_speed_kmh=270,
            ),
            TrackSegment(
                "Turn 14-15",
                "CORNER",
                0.95,
                1.00,
                250,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.80,
                regen_potential=0.45,
                max_speed_kmh=250,
            ),
        ],
        mini_sectors=[0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90],
    )


def monaco_2026() -> CircuitConfig:
    """Monaco — tight street circuit, minimal energy deployment, max regen."""
    return CircuitConfig(
        circuit_key="69",
        circuit_short_name="Monte Carlo",
        circuit_name="Circuit de Monaco",
        country="Monaco",
        total_laps=62,
        segments=[
            TrackSegment(
                "Casino Square",
                "CORNER",
                0.00,
                0.12,
                400,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.95,
                regen_potential=0.85,
                max_speed_kmh=280,
            ),
            TrackSegment(
                "La Rascasse",
                "CORNER",
                0.12,
                0.30,
                350,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.95,
                regen_potential=0.80,
                max_speed_kmh=260,
            ),
            TrackSegment(
                "Piscine",
                "CORNER",
                0.30,
                0.50,
                600,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.98,
                regen_potential=0.85,
                max_speed_kmh=270,
            ),
            TrackSegment(
                "Pont de l'Île",
                "CORNER",
                0.50,
                0.70,
                500,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.95,
                regen_potential=0.80,
                max_speed_kmh=260,
            ),
            TrackSegment(
                "Tunnel Straight",
                "STRAIGHT",
                0.70,
                0.78,
                300,
                key_accel_zone=True,
                overtake_value=0.15,
                downforce_demand=0.30,
                regen_potential=0.50,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Château d'Eau",
                "CORNER",
                0.78,
                0.90,
                300,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.95,
                regen_potential=0.75,
                max_speed_kmh=250,
            ),
            TrackSegment(
                "Hairpin",
                "CORNER",
                0.90,
                1.00,
                300,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.98,
                regen_potential=0.90,
                max_speed_kmh=220,
            ),
        ],
        mini_sectors=[0.14, 0.29, 0.43, 0.57, 0.71, 0.86],
    )


def spa_francorchamps_2026() -> CircuitConfig:
    """Spa-Francorchamps — high-speed, massive energy on long straights."""
    return CircuitConfig(
        circuit_key="74",
        circuit_short_name="Spa-Francorchamps",
        circuit_name="Circuit de Spa-Francorchamps",
        country="Belgium",
        total_laps=44,
        segments=[
            TrackSegment(
                "La Source",
                "CORNER",
                0.00,
                0.08,
                500,
                key_accel_zone=False,
                overtake_value=0.40,
                downforce_demand=0.80,
                regen_potential=0.75,
                max_speed_kmh=330,
            ),
            TrackSegment(
                "Eau Rouge",
                "CORNER",
                0.08,
                0.15,
                700,
                key_accel_zone=False,
                overtake_value=0.30,
                downforce_demand=0.95,
                regen_potential=0.70,
                max_speed_kmh=340,
            ),
            TrackSegment(
                "Kemmel Straight",
                "STRAIGHT",
                0.15,
                0.40,
                1900,
                key_accel_zone=True,
                overtake_value=0.95,
                downforce_demand=0.05,
                regen_potential=0.03,
                max_speed_kmh=370,
            ),
            TrackSegment(
                "Les Combes",
                "CORNER",
                0.40,
                0.48,
                350,
                key_accel_zone=False,
                overtake_value=0.70,
                downforce_demand=0.85,
                regen_potential=0.65,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Malmedy",
                "CORNER",
                0.48,
                0.62,
                650,
                key_accel_zone=False,
                overtake_value=0.20,
                downforce_demand=0.70,
                regen_potential=0.55,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Blanchimont",
                "CORNER",
                0.62,
                0.72,
                900,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.90,
                regen_potential=0.40,
                max_speed_kmh=330,
            ),
            TrackSegment(
                "Masta Kink",
                "STRAIGHT",
                0.72,
                0.85,
                700,
                key_accel_zone=True,
                overtake_value=0.80,
                downforce_demand=0.10,
                regen_potential=0.10,
                max_speed_kmh=340,
            ),
            TrackSegment(
                "Bus Stop",
                "CHICANE",
                0.85,
                0.95,
                400,
                key_accel_zone=False,
                overtake_value=0.15,
                downforce_demand=0.85,
                regen_potential=0.60,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Finish Straight",
                "STRAIGHT",
                0.95,
                1.00,
                350,
                key_accel_zone=True,
                overtake_value=0.50,
                downforce_demand=0.20,
                regen_potential=0.15,
                max_speed_kmh=320,
            ),
        ],
        mini_sectors=[0.10, 0.25, 0.40, 0.55, 0.70, 0.85],
    )


def monza_2026() -> CircuitConfig:
    """Monza — highest speed, maximum energy deployment demand."""
    return CircuitConfig(
        circuit_key="75",
        circuit_short_name="Monza",
        circuit_name="Autodromo Nazionale Monza",
        country="Italy",
        total_laps=53,
        segments=[
            TrackSegment(
                "Curva Raffaello",
                "CORNER",
                0.00,
                0.06,
                300,
                key_accel_zone=False,
                overtake_value=0.40,
                downforce_demand=0.90,
                regen_potential=0.60,
                max_speed_kmh=360,
            ),
            TrackSegment(
                "Retif",
                "CORNER",
                0.06,
                0.12,
                250,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.85,
                regen_potential=0.55,
                max_speed_kmh=340,
            ),
            TrackSegment(
                "Main Straight",
                "STRAIGHT",
                0.12,
                0.30,
                1050,
                key_accel_zone=True,
                overtake_value=0.90,
                downforce_demand=0.05,
                regen_potential=0.05,
                max_speed_kmh=380,
            ),
            TrackSegment(
                "Variante della Rampa",
                "CHICANE",
                0.30,
                0.36,
                250,
                key_accel_zone=False,
                overtake_value=0.60,
                downforce_demand=0.80,
                regen_potential=0.65,
                max_speed_kmh=330,
            ),
            TrackSegment(
                "Seconda Curva",
                "CORNER",
                0.36,
                0.48,
                400,
                key_accel_zone=True,
                overtake_value=0.30,
                downforce_demand=0.40,
                regen_potential=0.30,
                max_speed_kmh=350,
            ),
            TrackSegment(
                "Variante Ascari",
                "CHICANE",
                0.48,
                0.62,
                450,
                key_accel_zone=False,
                overtake_value=0.80,
                downforce_demand=0.85,
                regen_potential=0.55,
                max_speed_kmh=340,
            ),
            TrackSegment(
                "Back Straight",
                "STRAIGHT",
                0.62,
                0.80,
                800,
                key_accel_zone=True,
                overtake_value=0.90,
                downforce_demand=0.05,
                regen_potential=0.05,
                max_speed_kmh=380,
            ),
            TrackSegment(
                "Parabolica",
                "CORNER",
                0.80,
                1.00,
                950,
                key_accel_zone=False,
                overtake_value=0.25,
                downforce_demand=0.75,
                regen_potential=0.60,
                max_speed_kmh=330,
            ),
        ],
        mini_sectors=[0.12, 0.30, 0.48, 0.62, 0.80],
    )


def silverstone_2026() -> CircuitConfig:
    """Silverstone — fast, undulating, mixed energy demands."""
    return CircuitConfig(
        circuit_key="72",
        circuit_short_name="Silverstone",
        circuit_name="Silverstone Circuit",
        country="United Kingdom",
        total_laps=52,
        segments=[
            TrackSegment(
                "Turn 1",
                "CORNER",
                0.00,
                0.06,
                250,
                key_accel_zone=False,
                overtake_value=0.60,
                downforce_demand=0.80,
                regen_potential=0.70,
                max_speed_kmh=320,
            ),
            TrackSegment(
                "Copse",
                "CORNER",
                0.06,
                0.12,
                550,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.85,
                regen_potential=0.45,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Magotts-Becketts",
                "CORNER",
                0.12,
                0.30,
                1200,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.90,
                regen_potential=0.65,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Hangar Straight",
                "STRAIGHT",
                0.30,
                0.48,
                1100,
                key_accel_zone=True,
                overtake_value=0.80,
                downforce_demand=0.15,
                regen_potential=0.10,
                max_speed_kmh=340,
            ),
            TrackSegment(
                "Stowe",
                "CORNER",
                0.48,
                0.56,
                400,
                key_accel_zone=False,
                overtake_value=0.25,
                downforce_demand=0.85,
                regen_potential=0.70,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Club to Chapel",
                "CORNER",
                0.56,
                0.72,
                800,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.80,
                regen_potential=0.60,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Cavalier",
                "CORNER",
                0.72,
                0.85,
                500,
                key_accel_zone=True,
                overtake_value=0.15,
                downforce_demand=0.50,
                regen_potential=0.40,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Village to Start/Finish",
                "CORNER",
                0.85,
                1.00,
                700,
                key_accel_zone=False,
                overtake_value=0.30,
                downforce_demand=0.75,
                regen_potential=0.65,
                max_speed_kmh=300,
            ),
        ],
        mini_sectors=[0.15, 0.30, 0.48, 0.60, 0.75],
    )


def baku_2026() -> CircuitConfig:
    """Baku City Circuit — long straights, heavy braking, high overtake value."""
    return CircuitConfig(
        circuit_key="78",
        circuit_short_name="Baku",
        circuit_name="Baku City Circuit",
        country="Azerbaijan",
        total_laps=51,
        segments=[
            TrackSegment(
                "Turn 1 (Heavy Braking)",
                "CORNER",
                0.00,
                0.06,
                300,
                key_accel_zone=False,
                overtake_value=0.85,
                downforce_demand=0.85,
                regen_potential=0.85,
                max_speed_kmh=320,
            ),
            TrackSegment(
                "Start/Finish Straight",
                "STRAIGHT",
                0.06,
                0.22,
                1400,
                key_accel_zone=True,
                overtake_value=0.90,
                downforce_demand=0.10,
                regen_potential=0.05,
                max_speed_kmh=370,
            ),
            TrackSegment(
                "Turn 3-4",
                "CORNER",
                0.22,
                0.30,
                350,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.75,
                regen_potential=0.55,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Turn 5",
                "CORNER",
                0.30,
                0.38,
                200,
                key_accel_zone=True,
                overtake_value=0.30,
                downforce_demand=0.50,
                regen_potential=0.35,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Turn 8-9",
                "CHICANE",
                0.38,
                0.46,
                300,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.90,
                regen_potential=0.60,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Back Straight",
                "STRAIGHT",
                0.46,
                0.62,
                1200,
                key_accel_zone=True,
                overtake_value=0.85,
                downforce_demand=0.12,
                regen_potential=0.05,
                max_speed_kmh=365,
            ),
            TrackSegment(
                "Turn 15-16-17",
                "CORNER",
                0.62,
                0.80,
                600,
                key_accel_zone=False,
                overtake_value=0.40,
                downforce_demand=0.85,
                regen_potential=0.65,
                max_speed_kmh=280,
            ),
            TrackSegment(
                "Turn 18-19",
                "CORNER",
                0.80,
                0.92,
                500,
                key_accel_zone=False,
                overtake_value=0.25,
                downforce_demand=0.80,
                regen_potential=0.60,
                max_speed_kmh=270,
            ),
            TrackSegment(
                "Turn 20",
                "CORNER",
                0.92,
                1.00,
                250,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.90,
                regen_potential=0.75,
                max_speed_kmh=260,
            ),
        ],
        mini_sectors=[0.10, 0.25, 0.40, 0.55, 0.70, 0.85],
    )


def miami_2026() -> CircuitConfig:
    """Miami — high-speed sections mixed with tight chicanes."""
    return CircuitConfig(
        circuit_key="68",
        circuit_short_name="Miami",
        circuit_name="Miami International Autodrome",
        country="United States",
        total_laps=57,
        segments=[
            TrackSegment(
                "Turn 1",
                "CORNER",
                0.00,
                0.08,
                400,
                key_accel_zone=False,
                overtake_value=0.50,
                downforce_demand=0.80,
                regen_potential=0.70,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Start Straight",
                "STRAIGHT",
                0.08,
                0.22,
                500,
                key_accel_zone=True,
                overtake_value=0.60,
                downforce_demand=0.20,
                regen_potential=0.15,
                max_speed_kmh=330,
            ),
            TrackSegment(
                "Turn 3-4-5 Chican",
                "CHICANE",
                0.22,
                0.35,
                400,
                key_accel_zone=False,
                overtake_value=0.40,
                downforce_demand=0.85,
                regen_potential=0.70,
                max_speed_kmh=280,
            ),
            TrackSegment(
                "Back Straight",
                "STRAIGHT",
                0.35,
                0.55,
                1100,
                key_accel_zone=True,
                overtake_value=0.80,
                downforce_demand=0.10,
                regen_potential=0.05,
                max_speed_kmh=350,
            ),
            TrackSegment(
                "Turn 9-10-11",
                "CORNER",
                0.55,
                0.75,
                600,
                key_accel_zone=False,
                overtake_value=0.35,
                downforce_demand=0.85,
                regen_potential=0.65,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Turn 12-13",
                "CORNER",
                0.75,
                0.90,
                400,
                key_accel_zone=True,
                overtake_value=0.25,
                downforce_demand=0.50,
                regen_potential=0.40,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Turn 14-17",
                "CORNER",
                0.90,
                1.00,
                500,
                key_accel_zone=False,
                overtake_value=0.15,
                downforce_demand=0.80,
                regen_potential=0.60,
                max_speed_kmh=280,
            ),
        ],
        mini_sectors=[0.14, 0.30, 0.45, 0.62, 0.78],
    )


def singapore_2026() -> CircuitConfig:
    """Singapore — tight street circuit, high regen, low deploy."""
    return CircuitConfig(
        circuit_key="71",
        circuit_short_name="Singapore",
        circuit_name="Marina Bay Street Circuit",
        country="Singapore",
        total_laps=62,
        segments=[
            TrackSegment(
                "Turn 1",
                "CORNER",
                0.00,
                0.10,
                450,
                key_accel_zone=False,
                overtake_value=0.40,
                downforce_demand=0.90,
                regen_potential=0.80,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Turn 3-4",
                "CORNER",
                0.10,
                0.25,
                500,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.95,
                regen_potential=0.85,
                max_speed_kmh=260,
            ),
            TrackSegment(
                "Turn 5-6-7",
                "CORNER",
                0.25,
                0.45,
                700,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.95,
                regen_potential=0.90,
                max_speed_kmh=250,
            ),
            TrackSegment(
                "Turn 8",
                "CORNER",
                0.45,
                0.52,
                250,
                key_accel_zone=False,
                overtake_value=0.15,
                downforce_demand=0.90,
                regen_potential=0.75,
                max_speed_kmh=270,
            ),
            TrackSegment(
                "Turn 9-10",
                "CORNER",
                0.52,
                0.65,
                500,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.95,
                regen_potential=0.85,
                max_speed_kmh=260,
            ),
            TrackSegment(
                "Turn 11-12",
                "CORNER",
                0.65,
                0.78,
                400,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.90,
                regen_potential=0.80,
                max_speed_kmh=260,
            ),
            TrackSegment(
                "Turn 13-16",
                "CORNER",
                0.78,
                0.95,
                800,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.95,
                regen_potential=0.85,
                max_speed_kmh=270,
            ),
            TrackSegment(
                "Turn 17-23",
                "CORNER",
                0.95,
                1.00,
                700,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.95,
                regen_potential=0.90,
                max_speed_kmh=250,
            ),
        ],
        mini_sectors=[0.12, 0.25, 0.40, 0.52, 0.65, 0.78, 0.90],
    )


def austria_2026() -> CircuitConfig:
    """Red Bull Ring — short, high-speed, massive DRS zones."""
    return CircuitConfig(
        circuit_key="73",
        circuit_short_name="Spielberg",
        circuit_name="Red Bull Ring",
        country="Austria",
        total_laps=71,
        segments=[
            TrackSegment(
                "Turn 1",
                "CORNER",
                0.00,
                0.08,
                250,
                key_accel_zone=False,
                overtake_value=0.70,
                downforce_demand=0.75,
                regen_potential=0.70,
                max_speed_kmh=320,
            ),
            TrackSegment(
                "Start Straight",
                "STRAIGHT",
                0.08,
                0.28,
                1000,
                key_accel_zone=True,
                overtake_value=0.85,
                downforce_demand=0.08,
                regen_potential=0.05,
                max_speed_kmh=350,
            ),
            TrackSegment(
                "Turn 2-3",
                "CORNER",
                0.28,
                0.40,
                450,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.85,
                regen_potential=0.55,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Turn 4",
                "CORNER",
                0.40,
                0.50,
                200,
                key_accel_zone=True,
                overtake_value=0.10,
                downforce_demand=0.50,
                regen_potential=0.35,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Back Straight",
                "STRAIGHT",
                0.50,
                0.70,
                900,
                key_accel_zone=True,
                overtake_value=0.90,
                downforce_demand=0.05,
                regen_potential=0.03,
                max_speed_kmh=355,
            ),
            TrackSegment(
                "Turn 9-10",
                "CORNER",
                0.70,
                0.82,
                350,
                key_accel_zone=False,
                overtake_value=0.30,
                downforce_demand=0.80,
                regen_potential=0.60,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Turn 10-11",
                "CORNER",
                0.82,
                1.00,
                550,
                key_accel_zone=False,
                overtake_value=0.15,
                downforce_demand=0.85,
                regen_potential=0.65,
                max_speed_kmh=290,
            ),
        ],
        mini_sectors=[0.15, 0.30, 0.50, 0.70, 0.85],
    )


def catalunya_2026() -> CircuitConfig:
    """Circuit de Barcelona-Catalunya — mix of high and low speed."""
    return CircuitConfig(
        circuit_key="70",
        circuit_short_name="Catalunya",
        circuit_name="Circuit de Barcelona-Catalunya",
        country="Spain",
        total_laps=66,
        segments=[
            TrackSegment(
                "Turn 1",
                "CORNER",
                0.00,
                0.08,
                350,
                key_accel_zone=False,
                overtake_value=0.40,
                downforce_demand=0.80,
                regen_potential=0.70,
                max_speed_kmh=300,
            ),
            TrackSegment(
                "Turn 2-3",
                "CORNER",
                0.08,
                0.22,
                500,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.80,
                regen_potential=0.55,
                max_speed_kmh=280,
            ),
            TrackSegment(
                "Turn 4",
                "CORNER",
                0.22,
                0.30,
                250,
                key_accel_zone=True,
                overtake_value=0.10,
                downforce_demand=0.55,
                regen_potential=0.40,
                max_speed_kmh=310,
            ),
            TrackSegment(
                "Long Straight",
                "STRAIGHT",
                0.30,
                0.50,
                1000,
                key_accel_zone=True,
                overtake_value=0.85,
                downforce_demand=0.10,
                regen_potential=0.05,
                max_speed_kmh=345,
            ),
            TrackSegment(
                "Turn 9-10",
                "CORNER",
                0.50,
                0.60,
                400,
                key_accel_zone=False,
                overtake_value=0.15,
                downforce_demand=0.85,
                regen_potential=0.60,
                max_speed_kmh=290,
            ),
            TrackSegment(
                "Turn 11-13",
                "CORNER",
                0.60,
                0.80,
                700,
                key_accel_zone=False,
                overtake_value=0.10,
                downforce_demand=0.90,
                regen_potential=0.65,
                max_speed_kmh=280,
            ),
            TrackSegment(
                "Turn 14-16",
                "CORNER",
                0.80,
                1.00,
                800,
                key_accel_zone=False,
                overtake_value=0.05,
                downforce_demand=0.85,
                regen_potential=0.55,
                max_speed_kmh=290,
            ),
        ],
        mini_sectors=[0.15, 0.30, 0.50, 0.65, 0.80, 0.95],
    )


# ── Registry ──────────────────────────────────────────────────────────────

CIRCUIT_REGISTRY: dict[str, CircuitConfig] = {
    "bahrain": bahrain_sakhir_2026,
    "sakhir": bahrain_sakhir_2026,
    "monaco": monaco_2026,
    "spa": spa_francorchamps_2026,
    "monza": monza_2026,
    "silverstone": silverstone_2026,
    "baku": baku_2026,
    "miami": miami_2026,
    "singapore": singapore_2026,
    "austria": austria_2026,
    "spielberg": austria_2026,
    "catalunya": catalunya_2026,
    "spain": catalunya_2026,
}


def get_circuit_config(circuit_short_name: str) -> CircuitConfig | None:
    """Look up circuit config by short name (case-insensitive)."""
    key = circuit_short_name.lower().strip()
    factory = CIRCUIT_REGISTRY.get(key)
    if factory:
        return factory()
    return None


def get_circuit_config_by_key(circuit_key: str) -> CircuitConfig | None:
    """Look up circuit config by OpenF1 circuit_key."""
    for factory in CIRCUIT_REGISTRY.values():
        cfg = factory()
        if cfg.circuit_key == str(circuit_key):
            return cfg
    return None


def all_circuits() -> list[CircuitConfig]:
    """Return all registered circuit configs."""
    return [f() for f in CIRCUIT_REGISTRY.values()]
