"""initial_live_schema

Revision ID: 1373539546e8
Revises: 
Create Date: 2026-09-23 03:28:07.378041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1373539546e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('meeting_key', sa.String(length=64), nullable=True),
    sa.Column('session_key', sa.String(length=64), nullable=True),
    sa.Column('session_name', sa.String(length=128), nullable=True),
    sa.Column('session_type', sa.String(length=64), nullable=True),
    sa.Column('circuit_key', sa.String(length=64), nullable=True),
    sa.Column('circuit_name', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('track_status', sa.String(length=32), nullable=False),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.Column('current_lap', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('live_driver_laps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_s', sa.Float(), nullable=True),
    sa.Column('sector_1_s', sa.Float(), nullable=True),
    sa.Column('sector_2_s', sa.Float(), nullable=True),
    sa.Column('sector_3_s', sa.Float(), nullable=True),
    sa.Column('compound', sa.String(length=32), nullable=True),
    sa.Column('tyre_age', sa.Integer(), nullable=True),
    sa.Column('stint_no', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('gap_to_leader_s', sa.Float(), nullable=True),
    sa.Column('interval_s', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_pit_in', sa.Boolean(), nullable=False),
    sa.Column('is_pit_out', sa.Boolean(), nullable=False),
    sa.Column('track_status', sa.String(length=32), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_number', 'lap_number', name='uq_live_driver_laps_session_driver_lap')
    )
    with op.batch_alter_table('live_driver_laps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_driver_laps_driver_number'), ['driver_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_driver_laps_lap_number'), ['lap_number'], unique=False)
        batch_op.create_index('ix_live_driver_laps_session_driver', ['session_id', 'driver_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_driver_laps_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_live_driver_laps_session_lap', ['session_id', 'lap_number'], unique=False)

    op.create_table('live_hazard_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('hazard_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('flag', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('p_sc', sa.Float(), nullable=True),
    sa.Column('p_vsc', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(length=32), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_hazard_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_hazard_logs_driver_number'), ['driver_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_hazard_logs_lap_number'), ['lap_number'], unique=False)
        batch_op.create_index('ix_live_hazard_logs_session_driver', ['session_id', 'driver_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_hazard_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_live_hazard_logs_session_lap', ['session_id', 'lap_number'], unique=False)

    op.create_table('live_stints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('stint_no', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=32), nullable=False),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=True),
    sa.Column('tyre_age_start', sa.Integer(), nullable=False),
    sa.Column('tyre_age_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_number', 'stint_no', name='uq_live_stints_session_driver_stint')
    )
    with op.batch_alter_table('live_stints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_stints_driver_number'), ['driver_number'], unique=False)
        batch_op.create_index('ix_live_stints_session_driver', ['session_id', 'driver_number'], unique=False)
        batch_op.create_index('ix_live_stints_session_driver_stint', ['session_id', 'driver_number', 'stint_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_stints_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_stints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_stints_session_id'))
        batch_op.drop_index('ix_live_stints_session_driver_stint')
        batch_op.drop_index('ix_live_stints_session_driver')
        batch_op.drop_index(batch_op.f('ix_live_stints_driver_number'))

    op.drop_table('live_stints')
    with op.batch_alter_table('live_hazard_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_live_hazard_logs_session_lap')
        batch_op.drop_index(batch_op.f('ix_live_hazard_logs_session_id'))
        batch_op.drop_index('ix_live_hazard_logs_session_driver')
        batch_op.drop_index(batch_op.f('ix_live_hazard_logs_lap_number'))
        batch_op.drop_index(batch_op.f('ix_live_hazard_logs_driver_number'))

    op.drop_table('live_hazard_logs')
    with op.batch_alter_table('live_driver_laps', schema=None) as batch_op:
        batch_op.drop_index('ix_live_driver_laps_session_lap')
        batch_op.drop_index(batch_op.f('ix_live_driver_laps_session_id'))
        batch_op.drop_index('ix_live_driver_laps_session_driver')
        batch_op.drop_index(batch_op.f('ix_live_driver_laps_lap_number'))
        batch_op.drop_index(batch_op.f('ix_live_driver_laps_driver_number'))

    op.drop_table('live_driver_laps')
    op.drop_table('live_sessions')
    # ### end Alembic commands ###
