"""add_weather_and_event_records

Revision ID: 5357a6487f66
Revises: 1373539546e8
Create Date: 2026-09-23 11:52:07.938443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5357a6487f66'
down_revision: Union[str, Sequence[str], None] = '1373539546e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_event_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('source_key', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_event_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_event_records_driver_number'), ['driver_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_event_records_event_ts'), ['event_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_event_records_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_event_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_live_events_session_ts', ['session_id', 'event_ts'], unique=False)
        batch_op.create_index('ix_live_events_session_type', ['session_id', 'event_type'], unique=False)

    op.create_table('live_weather_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('air_temp_c', sa.Float(), nullable=True),
    sa.Column('track_temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('pressure_mbar', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_dir_deg', sa.Integer(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('rainfall_prob', sa.Float(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_weather_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_weather_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_weather_records_source_timestamp'), ['source_timestamp'], unique=False)
        batch_op.create_index('ix_live_weather_session_time', ['session_id', 'source_timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_weather_records', schema=None) as batch_op:
        batch_op.drop_index('ix_live_weather_session_time')
        batch_op.drop_index(batch_op.f('ix_live_weather_records_source_timestamp'))
        batch_op.drop_index(batch_op.f('ix_live_weather_records_session_id'))

    op.drop_table('live_weather_records')
    with op.batch_alter_table('live_event_records', schema=None) as batch_op:
        batch_op.drop_index('ix_live_events_session_type')
        batch_op.drop_index('ix_live_events_session_ts')
        batch_op.drop_index(batch_op.f('ix_live_event_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_live_event_records_event_type'))
        batch_op.drop_index(batch_op.f('ix_live_event_records_event_ts'))
        batch_op.drop_index(batch_op.f('ix_live_event_records_driver_number'))

    op.drop_table('live_event_records')
    # ### end Alembic commands ###
